name: Backend Continuous Deployment to GCP Cloud Run  
on:
  push:
    branches:
      - main
  workflow_dispatch: {}
permissions:
  contents: read
  id-token: write 
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: ${{ steps.deploy-to-cloud-run.outputs.url }} 
    env:
      PROJECT_ID: oidc-gcp-roland-01
      DOCKER_USERNAME: ${{ secrets.DOCKERHUB_LOR2P }}
      DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
      BACKEND_IMAGE: blog-backend
      PROJECT_NUMBER: "591006590099"
      workload_identity_pool: my-github-pool
      WIF_PROVIDER: "projects/591006590099/locations/global/workloadIdentityPools/my-github-pool/providers/my-github-provider"
      WIF_SA: cloudrun-deployer@oidc-gcp-roland-01.iam.gserviceaccount.com
    steps:
      - uses: actions/checkout@v4
      # Docker Hub Login
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}
      # Authenticate to GCP authentication using Workload Identity Federation
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ env.WIF_PROVIDER }}
          service_account: ${{ env.WIF_SA }}
      # Configure gcloud CLI
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          install_components: "gke-gcloud-auth-plugin"
      # Build and Push Docker Image to Docker Hub
      - name: Build and Push Docker Image
        run: |
          docker build --platform linux/amd64  -t ${{ env.DOCKER_USERNAME }}/${{ env.BACKEND_IMAGE }}:latest -f ./backend/Dockerfile .
          docker push ${{ env.DOCKER_USERNAME }}/${{ env.BACKEND_IMAGE }}:latest
      # Deploy to Cloud Run
      - name: Deploy to Cloud Run
        id: deploy-to-cloud-run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: blog-backend-service
          //image: ${{ env.DOCKER_USERNAME }}/${{ env.BACKEND_IMAGE }}:latest
          image: us-central1-docker.pkg.dev/oidc-gcp-roland-01/blog/blog-backend:latest
          region: ${{ secrets.GOOGLECLOUD_REGION }}
          platform: managed   