name: Backend Continuous Deployment to GCP Cloud Run

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: ${{ steps.deploy-to-cloud-run.outputs.url }}
    env:
      PROJECT_ID: oidc-gcp-roland-01
      PROJECT_NUMBER: "591006590099"
      REGION: us-central1
      REPOSITORY: blog
      IMAGE_NAME: blog-backend
      WIF_PROVIDER: "projects/591006590099/locations/global/workloadIdentityPools/my-github-pool/providers/my-github-provider"
      WIF_SA: cloudrun-deployer@oidc-gcp-roland-01.iam.gserviceaccount.com

    steps:
      - uses: actions/checkout@v4

      # Authenticate to Google Cloud
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ env.WIF_PROVIDER }}
          service_account: ${{ env.WIF_SA }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      # Build and Push Image to Artifact Registry
      - name: Build and Push Image to Artifact Registry
        run: |
          IMAGE="us-central1-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/${IMAGE_NAME}:${GITHUB_SHA}"
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

          gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

          docker build \
            --platform linux/amd64 \
            -t "$IMAGE" \
            -f backend/Dockerfile \
            backend/

          docker push "$IMAGE"

      # Deploy to Cloud Run
      - name: Deploy to Cloud Run
        id: deploy-to-cloud-run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: blog-backend-service
          image: ${{ env.IMAGE }}
          region: ${{ env.REGION }}
          flags: "--allow-unauthenticated"
